/// Permission to use, copy, modify, and/or distribute this software for any
/// purpose with or without fee is hereby granted.
///
/// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
/// REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
/// AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
/// INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
/// LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
/// OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
/// PERFORMANCE OF THIS SOFTWARE.
#ifndef ASRTL_ECODE_H
#define ASRTL_ECODE_H

#ifdef __cplusplus
extern "C" {
#endif

enum asrtl_ecode
{
        ASRTL_ASE1                     = 1,
        ASRTL_ASE_MISSING_TEST         = ASRTL_ASE1,
        ASRTL_ASE2                     = 2,
        ASRTL_ASE_TEST_ALREADY_RUNNING = ASRTL_ASE2,
};

#ifdef __cplusplus
}
#endif

#endif
